name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install buildozer
        run: pip install buildozer cython
      - name: Build
        run: buildozer android debug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: bin/*.apk
